" Nice colors
syntax on
set background=dark
colorscheme jellybeans
" same for the satusline
let g:airline_theme='jellybeans'

" always show statusline
set laststatus=2

" don't behave like the old vim, we need it for most plugins
set nocompatible

" allow per file settings if a modeline is found
set modeline

" display tabs and trailing spaces
set list listchars=tab:»·,trail:·

" set backup / swap dir
set backupdir=~/.vim_cache//
set directory=~/.vim_cache//
" activate and set undo files location
set udf
set udir=~/.vim_cache//

" improve tab bar
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" use 256 colours
if has('unix')
    set t_Co=256
endif

" unite.vim mappings
nnoremap <Leader>f :Unite file<CR>
nnoremap <Leader>b :Unite buffer<CR>
nnoremap <Leader>t :Unite tab<CR>
" file explorer mode
nnoremap <Leader>e :Explore<CR>
