" Nice colors
syntax on
set background=dark
colorscheme jellybeans
" same for the satusline
let g:airline_theme='jellybeans'

" always show statusline
set laststatus=2

" don't behave like the old vim, we need it for most plugins
set nocompatible

" allow per file settings if a modeline is found
set modeline

" display tabs and trailing spaces
set list listchars=tab:»·,trail:·

" set backup / swap dir
set backupdir=~/.vim_cache//
set directory=~/.vim_cache//
" activate and set undo files location
set udf
set udir=~/.vim_cache//

" improve tab bar
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" use 256 colours
if has('unix')
    set t_Co=256
endif

" unite.vim mappings
call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <leader>t :<C-u>Unite -buffer-name=tab    -start-insert tab<cr>
nnoremap <leader>r :<C-u>Unite -buffer-name=files  -start-insert file_rec<cr>
nnoremap <leader>f :<C-u>Unite -buffer-name=files  -start-insert file<cr>
nnoremap <leader>b :<C-u>Unite -buffer-name=buffer -start-insert buffer<cr>
nnoremap <leader>h :<C-u>Unite -buffer-name=help   -start-insert help<cr>
" file explorer mode
nnoremap <Leader>e :Explore<CR>
