# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# User specific aliases and functions
# test if a file exists before sourcing it, warn the user otherwise
include_file() {
  local included_file=$1
  if [ -f "${included_file}" ]; then
    . "${included_file}"
  else
    echo "Not sourcing ${included_file}, it doesn't exists."
  fi
}

