# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# include prompt configuration
include_file ~/.bash_prompt

# User specific environment and startup programs
if [ -d "$HOME/bin" ] ; then
  pathprepend $HOME/bin
fi

export PATH

# vim: set filetype=sh:
